#! /bin/bash

svn update
cd src
make clean
make EXT=JETI
mv er9x.hex ../er9x-jeti.hex
make clean
make EXT=FRSKY
mv er9x.hex ../er9x-frsky.hex
make clean
make EXT=STD BEEPER=BUZZER KEYRPT=STD
mv er9x.hex ../er9x-stock.hex
make clean 
make EXT=FRSKY BEEPER=SPEAKER KEYRPT=DELAY
mv er9x.hex ../gruvin9x.hex
make clean

