#! /bin/bash

cd src

# Build current development defaults version
TARGET=gruvin9x
make clean TARGET=$TARGET
make TARGET=$TARGET
mv $TARGET.hex ..
make clean TARGET=$TARGET


# Build stock and near-stock hardware versions ...
TARGET=gruvin9x-stock
make clean TARGET=$TARGET
make TARGET=$TARGET PCB=STD EXT=STD BEEPER=BUZZER USART1=STD PPMIN=STD
mv $TARGET.hex ..
make clean TARGET=$TARGET

TARGET=gruvin9x-std-speaker
make clean TARGET=$TARGET
make TARGET=$TARGET PCB=STD BEEPER=SPEAKER USART1=STD PPMIN=STD
mv $TARGET.hex ..
make clean TARGET=$TARGET

TARGET=gruvin9x-frsky-nospeaker
make clean TARGET=$TARGET
make TARGET=$TARGET PCB=STD EXT=FRSKY BEEPER=BUZZER USART1=STD PPMIN=STD
mv $TARGET.hex ..
make clean TARGET=$TARGET

TARGET=gruvin9x-frsky-speaker
make clean TARGET=$TARGET
make TARGET=$TARGET PCB=STD EXT=FRSKY BEEPER=SPEAKER USART1=STD PPMIN=STD
mv $TARGET.hex ..
make clean TARGET=$TARGET

cd ..
# Create version info gif file for Google wiki
./svnversion.sh
