#! /bin/bash

cd src

# Build fully Gruvinized version ...
make clean 
make
mv gruvin9x.hex ../gruvin9x.hex

# Build stock and near-stock hardware versions ...
make clean
make PCB=STD EXT=STD BEEPER=BUZZER USART1=STD PPMIN=STD
mv gruvin9x.hex ../gruvin9x-stock.hex

make clean
make PCB=STD BEEPER=SPEAKER USART1=STD PPMIN=STD
mv gruvin9x.hex ../gruvin9x-std-speaker.hex

make clean
make PCB=STD EXT=FRSKY BEEPER=BUZZER USART1=STD PPMIN=STD
mv gruvin9x.hex ../gruvin9x-frsky-nospeaker.hex

make clean
make PCB=STD EXT=FRSKY BEEPER=SPEAKER USART1=STD PPMIN=STD
mv gruvin9x.hex ../gruvin9x-frsky-speaker.hex

make clean
make PCB=V2
mv gruvin9x.hex ../gruvin9x-v2-pcb.hex

make clean
